version: "3.7"
services:
  komodo_relay:
    build: .
    image: komodo-relay:latest
    container_name: komodo-relay
    restart: "always"
    volumes: 
        - ../captures:/komodo/captures
    labels:
      - "traefik.frontend.rule=Host:relay.komodo-dev.library.illinois.edu"
      - "traefik.backend=komodo_relay"
      - "traefik.port=3000"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
    networks: 
      - proxy

networks: 
  proxy:
    external: true