version: "3.7"
services:
  relay:
    build: .
    image: komodo-relay:latest
    container_name: komodo-relay
    restart: "always"
    volumes: 
        - ../captures:/komodo/captures
    labels:
      - "traefik.frontend.rule=Host:relay.komodo-dev.library.illinois.edu"
      - "traefik.relay.backend=komodo-relay"
      - "traefik.relay.port=3000"
      - "traefik.peer.backend=komodo-relay"
      - "traefik.peer.port=9000"
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
    networks: 
      - proxy
      - komodo_internal

networks: 
  proxy:
    external: true
  komodo_internal:
    external: true